spring:
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    timeout: 10000

    lettuce:
      pool:
        max-idle: 20
        min-idle: 5
        max-active: 100
        max-wait: 6000
    password:
